package tests

import (
	"testing"
)

// TestPhase9_GetTextOnFormElements tests that GetText correctly returns
// meaningful content for form elements (input, textarea, select) where
// innerText/textContent is always empty.
// This was a bug: "kbr get text <id>" returned empty for textbox elements.
func TestPhase9_GetTextOnFormElements(t *testing.T) {
	b := newBrowser(t)
	openPage(t, b, "phase9_get_test.html")
	snap := mustSnapshot(t, b)
	t.Logf("Snapshot:\n%s", snap.Text)

	searchID := findID(t, snap.Text, `textbox "Search"`)
	emptyInputID := findID(t, snap.Text, `textbox "Empty Input"`)
	commentID := findID(t, snap.Text, `textbox "Comment"`)
	colorID := findID(t, snap.Text, `combobox "Color"`)
	buttonID := findID(t, snap.Text, `button "Click Me"`)
	passwordID := findID(t, snap.Text, `textbox "Password"`)

	// === GetText on form elements ===

	t.Run("GetText_input_with_value", func(t *testing.T) {
		text, err := b.GetText(searchID)







































































































































































































































}	})		assertEqual(t, val, "hello world")		must(t, err)		val, err := b.GetValue(searchID)	t.Run("GetValue_input_after_DOM_mutation", func(t *testing.T) {	})		assertContains(t, html, "input")		}			t.Fatal("GetHTML on input returned empty after DOM mutation")		if html == "" {		must(t, err)		html, err := b.GetHTML(searchID)	t.Run("GetHTML_input_after_DOM_mutation", func(t *testing.T) {	})		assertEqual(t, text, "Click Me")		must(t, err)		text, err := b.GetText(buttonID)	t.Run("GetText_button_after_DOM_mutation", func(t *testing.T) {	})		assertEqual(t, text, "hello world")		must(t, err)		text, err := b.GetText(searchID)	t.Run("GetText_input_after_DOM_mutation", func(t *testing.T) {	// Now get text using old IDs — should still work (via refresh or fallback)	must(t, err)	_, err := b.Eval(`document.getElementById('info-para').remove()`)	// Mutate the DOM slightly via JS to potentially invalidate backend node IDs	buttonID := findID(t, snap.Text, `button "Click Me"`)	searchID := findID(t, snap.Text, `textbox "Search"`)	snap := mustSnapshot(t, b)	// Take first snapshot	openPage(t, b, "phase9_get_test.html")	b := newBrowser(t)func TestPhase9_GetAfterSnapshotRefresh(t *testing.T) {// between snapshot and get command.// This simulates the original bug where the page's DOM might have changed// even after the page has potentially changed (stale backend node IDs).// TestPhase9_GetAfterSnapshotRefresh tests that get commands still work}	}		t.Log("image not found in snapshot, skipping img test")	} else {		})			assertContains(t, html, `alt="Logo"`)			assertContains(t, html, "img")			}				t.Fatal("GetHTML on <img> returned empty string")			if html == "" {			must(t, err)			html, err := b.GetHTML(imgID)		t.Run("GetHTML_img_returns_outerHTML", func(t *testing.T) {	if imgID > 0 {	}		imgID = tryFindID(snap.Text, `image`)	if imgID == 0 {	imgID := tryFindID(snap.Text, `image "Logo"`)	// img is a void element — innerHTML is always "", should get outerHTML	})		assertContains(t, html, "<em>Example</em>")		assertContains(t, html, "Visit")		must(t, err)		html, err := b.GetHTML(linkID)	t.Run("GetHTML_link_with_nested_content", func(t *testing.T) {	linkID := findID(t, snap.Text, `link "Visit Example"`)	t.Logf("Snapshot:\n%s", snap.Text)	snap := mustSnapshot(t, b)	openPage(t, b, "phase9_get_test.html")	b := newBrowser(t)func TestPhase9_GetHTMLOnNonInteractiveElements(t *testing.T) {// and void elements like <img>.// TestPhase9_GetHTMLOnNonInteractiveElements tests GetHTML on regular elements}	}		})			assertContains(t, text, "Status: OK")			must(t, err)			text, err := b.GetText(statusID)		t.Run("GetText_status_div", func(t *testing.T) {	if statusID > 0 {	statusID := tryFindID(snap.Text, `status`)	// Status div might or might not appear in snapshot depending on role visibility	})		assertContains(t, text, "Example")		assertContains(t, text, "Visit")		must(t, err)		text, err := b.GetText(linkID)	t.Run("GetText_link", func(t *testing.T) {	})		assertEqual(t, text, "Get Command Test")		must(t, err)		text, err := b.GetText(headingID)	t.Run("GetText_heading", func(t *testing.T) {	linkID := findID(t, snap.Text, `link "Visit Example"`)	headingID := findID(t, snap.Text, `heading "Get Command Test"`)	t.Logf("Snapshot:\n%s", snap.Text)	snap := mustSnapshot(t, b)	openPage(t, b, "phase9_get_test.html")	b := newBrowser(t)func TestPhase9_GetTextOnNonInteractiveElements(t *testing.T) {// These go through the regular innerText path, not the form-element special case.// that are not interactive (e.g., heading, paragraph, link, status div).// TestPhase9_GetTextOnNonInteractiveElements tests GetText on elements}	})		assertEqual(t, val, "secret123")		must(t, err)		val, err := b.GetValue(passwordID)	t.Run("GetValue_password", func(t *testing.T) {	})		assertEqual(t, val, "green")		must(t, err)		val, err := b.GetValue(colorID)	t.Run("GetValue_select", func(t *testing.T) {	})		assertEqual(t, val, "This is a comment")		must(t, err)		val, err := b.GetValue(commentID)	t.Run("GetValue_textarea", func(t *testing.T) {	})		assertEqual(t, val, "")		must(t, err)		val, err := b.GetValue(emptyInputID)	t.Run("GetValue_empty_input", func(t *testing.T) {	})		assertEqual(t, val, "hello world")		must(t, err)		val, err := b.GetValue(searchID)	t.Run("GetValue_input_with_value", func(t *testing.T) {	passwordID := findID(t, snap.Text, `textbox "Password"`)	colorID := findID(t, snap.Text, `combobox "Color"`)	commentID := findID(t, snap.Text, `textbox "Comment"`)	emptyInputID := findID(t, snap.Text, `textbox "Empty Input"`)	searchID := findID(t, snap.Text, `textbox "Search"`)	t.Logf("Snapshot:\n%s", snap.Text)	snap := mustSnapshot(t, b)	openPage(t, b, "phase9_get_test.html")	b := newBrowser(t)func TestPhase9_GetValueOnFormElements(t *testing.T) {// TestPhase9_GetValueOnFormElements tests that GetValue works on all form elements.}	})		assertEqual(t, html, "Click Me")		must(t, err)		html, err := b.GetHTML(buttonID)	t.Run("GetHTML_button_returns_innerHTML", func(t *testing.T) {	})		assertContains(t, html, `value="hello world"`)		assertContains(t, html, "input")		}			t.Fatal("GetHTML on input returned empty string (the original bug)")		if html == "" {		// Should fall back to outerHTML.		// Input is a void element — innerHTML is always "".		must(t, err)		html, err := b.GetHTML(searchID)	t.Run("GetHTML_input_returns_outerHTML", func(t *testing.T) {	buttonID := findID(t, snap.Text, `button "Click Me"`)	searchID := findID(t, snap.Text, `textbox "Search"`)	t.Logf("Snapshot:\n%s", snap.Text)	snap := mustSnapshot(t, b)	openPage(t, b, "phase9_get_test.html")	b := newBrowser(t)func TestPhase9_GetHTMLOnFormElements(t *testing.T) {// content for void/form elements (where innerHTML is always empty).// TestPhase9_GetHTMLOnFormElements tests that GetHTML returns meaningful}	})		assertEqual(t, text, "secret123")		// Password input has value="secret123"		must(t, err)		text, err := b.GetText(passwordID)	t.Run("GetText_password_input", func(t *testing.T) {	})		assertEqual(t, text, "Click Me")		must(t, err)		text, err := b.GetText(buttonID)	t.Run("GetText_button", func(t *testing.T) {	})		assertContains(t, text, "Green")		// Select should return the selected option's text		must(t, err)		text, err := b.GetText(colorID)	t.Run("GetText_select", func(t *testing.T) {	})		assertContains(t, text, "This is a comment")		must(t, err)		text, err := b.GetText(commentID)	t.Run("GetText_textarea", func(t *testing.T) {	})		assertEqual(t, text, "请输入内容")		// Empty value but has placeholder → should return placeholder		must(t, err)		text, err := b.GetText(emptyInputID)	t.Run("GetText_input_empty_value_with_placeholder", func(t *testing.T) {	})		assertEqual(t, text, "hello world")		// Input with value="hello world" → should return "hello world", not ""		must(t, err)